### ISSUE TITLE
Mancala house rules

### ISSUE THREAD

**Issue by StrangerCoug** [StrangerCoug/FreeCardAndBoard#2]
**Is your feature request related to a problem? Please describe.**
The rules for Mancala are programmed according to the Kalah page on Wikipedia; however, the rules there are not the exact ruleset @charleshammer were used to when he was testing the game. As Mancala is sometimes played slightly differently among different players, one set of rules should be set as a reasonable default while less agreed-upon but still popular rules should be allowed at a player's discretion.

**Describe the solution you'd like**
The player (or the host, if an online game among humans) should be offered, in an intuitive interface, the option to change the rules to better suit how they are used to playing, for example:
1. Should empty captures be allowed?
2. Who should get the remaining stones once a player can no longer play?

**Describe alternatives you've considered**
In theory, it is possible to reprogram the rules to a different set; however, as Mancala has no official rules, it cannot reasonably be done in a way that satisfies all players.

**Additional context**
Two sources of rules:
[Wikipedia page on Kalah](https://en.wikipedia.org/wiki/Kalah) (source for currently programmed rules)
[Ruleset issued with one physical copy of the game](https://endlessgames.com/wp-content/uploads/Mancala_Instructions.pdf) (provided by @charleshammer )

**Comment by charleshammer** [comment]
I think there is no problem here. The Wikipedia seems to agree with the endlessgames ruleset

**Comment by StrangerCoug** [comment]
I see that. However, it might still be a good idea to ask if a player wants to allow empty captures, since Wikipedia admits it as a nonstandard variation.

**Comment by charleshammer** [comment]
from endlessgames:
 5. If the last piece you drop is in an empty pocket on your side, you capture that piece and any pieces in the pocket directly
opposite.

That seems to be allowing empty captures as the official rule

**Comment by StrangerCoug** [comment]
Added the rule allowing empty captures as an option and defaulted to permitting them. Any others you think would be interesting?

**Comment by charleshammer** [comment]
optionally allow 5 stones in starting bins or any number

**Comment by StrangerCoug** [comment]
I like that idea :)

**Comment by StrangerCoug** [comment]
Closing due to archiving repository.
